# -*- coding: utf-8 -*-
"""spleeter-service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8LKJ-CchYmOPgqgtM_WXGJjMn9RRnMF
"""

# Mount Drive and install Spleeter
from google.colab import drive
drive.mount('/content/drive')
!pip install spleeter

# Setup and Processing
import os
import time

# Setup folders
AUDIO_ROOT = '/content/drive/MyDrive/AudioSplitter'
os.makedirs(f'{AUDIO_ROOT}/input', exist_ok=True)
os.makedirs(f'{AUDIO_ROOT}/output', exist_ok=True)

def process_audio(input_path):
    """Process single audio file with Spleeter"""
    try:
        output_dir = f'{AUDIO_ROOT}/output'
        !spleeter separate -p spleeter:2stems -o {output_dir} "{input_path}"
        return True
    except Exception as e:
        print(f"Error processing {input_path}: {str(e)}")
        return False

print("🎵 Audio Splitter Service Started 🎵")
while True:
    # Check input folder
    input_files = os.listdir(f'{AUDIO_ROOT}/input')

    for file in input_files:
        if file.endswith('.wav'):
            input_path = f'{AUDIO_ROOT}/input/{file}'
            print(f"\nProcessing: {file}")

            if process_audio(input_path):
                print("✅ Processing complete")
                # Clean up input file
                os.remove(input_path)
            else:
                print("❌ Processing failed")

    time.sleep(5)  # Check every 5 seconds